In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

sales_purchases = pd.read_csv("missing_tax_type_taxpayer_sample_dataset_sales_and_purchases.csv")
taxpayers_tax_types_df = pd.read_csv("missing_tax_type_taxpayer_sample_dataset_registration.csv")
# import_export = pd.read_csv("missing_tax_type_taxpayer_sample_dataset_imports_and_exports.csv")

# resident_individual if have date is personal income tax 
taxpayers_tax_types_df = taxpayers_tax_types_df[["masked_pin","gender","year_of_birth","resident_individual","turnover_tax"]]

taxpayers_tax_types_df['resident_individual'] = taxpayers_tax_types_df['resident_individual'].notna().astype(int)
taxpayers_tax_types_df['turnover_tax'] = taxpayers_tax_types_df['turnover_tax'].notna().astype(int)

taxpayers_tax_types_df = taxpayers_tax_types_df.fillna(
    {'gender': 'MISSING'}
)

In [ ]:
sales_purchases = sales_purchases.groupby(["masked_pin","year"]).agg({
    "b2b_nber_of_invoices":sum,	"b2b_sales_amount":sum,	"b2c_nber_of_invoices":sum,	"b2c_sales_amount":sum,	"purchases_nber_of_invoices":sum,	"purchases_amount":sum
}).reset_index()

upgrade_from_turnover_tax = pd.merge(sales_purchases, taxpayers_tax_types_df, left_on="masked_pin", right_on="masked_pin", how="left")

upgrade_from_turnover_tax["Sales"] = upgrade_from_turnover_tax["b2b_sales_amount"] + upgrade_from_turnover_tax["b2c_sales_amount"]
upgrade_from_turnover_tax["Purchases"] = upgrade_from_turnover_tax["purchases_amount"]

upgrade_from_turnover_tax = upgrade_from_turnover_tax[(upgrade_from_turnover_tax["year"] == upgrade_from_turnover_tax["year"].max()) & (upgrade_from_turnover_tax["Sales"] >= 25000000) & (upgrade_from_turnover_tax["turnover_tax"] == 1) & (upgrade_from_turnover_tax["resident_individual"] == 0)].reset_index(drop=True)
upgrade_from_turnover_tax[['masked_pin','gender','year_of_birth', 'resident_individual', 'turnover_tax', 'year', 'b2b_nber_of_invoices', 'b2b_sales_amount',
       'b2c_nber_of_invoices', 'b2c_sales_amount','purchases_nber_of_invoices', 'purchases_amount', 'Sales','Purchases']]

/tmp/ipykernel_148952/3783151753.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sales_purchases = sales_purchases.groupby(["masked_pin","year"]).agg({
/tmp/ipykernel_148952/3783151753.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sales_purchases = sales_purchases.groupby(["masked_pin","year"]).agg({

Empty DataFrame
Columns: [masked_pin, gender, year_of_birth, resident_individual, turnover_tax, year, b2b_nber_of_invoices, b2b_sales_amount, b2c_nber_of_invoices, b2c_sales_amount, purchases_nber_of_invoices, purchases_amount, Sales, Purchases]
Index: []

In [ ]:
taxpayers_tax_types_df[taxpayers_tax_types_df['turnover_tax']==1]

,masked_pin,gender,year_of_birth,resident_individual,turnover_tax
32,001bcf34727f0f16b4af71eafe2398ee1876a5a598296b...,M,1970.0,1,1
670,001785ce4e843415ada184bde1d7b9aa94bf9479cb3462...,M,1979.0,1,1
704,0010b7d1d537c1fdc33b345948f3cc91afad611bd05cbf...,F,1966.0,1,1
780,00024b5734a1dcd7f270ae7aaf39f43f06278f7641a5ad...,F,1989.0,1,1
955,0006cf303db1099ea908f15f20334f6861548abc252d46...,MISSING,1987.0,0,1
1848,000876da5161c5049904dc4326a00200d547426128c2e4...,F,1984.0,1,1
2396,000de595a6e1b70f7d7e95715e5959f02f3416e535de07...,F,1989.0,1,1
3232,001907eff2a894eaf0422f0e5e9e452fc37181c10429b8...,F,1958.0,1,1
3241,0015b8cccbe4fcbc40c9efa9bfa8f5ae87d2ff5c3598c5...,M,1962.0,1,1
3876,00151a3edcdb05f06a0dbd4144a4aed30624cf4f91fa5b...,M,1967.0,1,1
3970,001829429129584e2d9d207620f30d95c225054576e7b7...,F,1991.0,1,1
4233,001907da21274ba876811513a39e003a503afb51a57b2a...,F,1977.0,1,1
5118,001a2cbeac57cb66ebebff3beb7381a4fdc9a9e99bc213...,M,1994.0,1,1
5121,000edfc497e1f53c145eafa5a723a4a7df4143c07f9ec0...,M,1995.0,1,1
5260,0015170109e3d76db10a02736eff80c0ed10dc22675800...,M,1987.0,1,1
6157,00036348b9f28b44c028dd835dbbece1bcb7775e428903...,M,1958.0,1,1
6616,001c6504a988c3d927759663e550b7ce48d3a0cc65b410...,M,1995.0,1,1
6822,00102a5adde713899b49b59a08c1eb8b75c44aa8cadecd...,F,1983.0,1,1
6858,000a1c3edf098822bd9d8c3ec68b19925b13077519c664...,F,1965.0,1,1
7108,000e89363c3cbb8328011b19abd7c02b7c7073ad0486a8...,F,1990.0,1,1
7615,000a34a954e4f99054c2aceca3e3a15903a834eeedd97a...,M,1993.0,1,1
8742,00192fbfcd401c4ffd7e444a966579d5f7e2e1a063ac33...,MISSING,1962.0,0,1
8773,00113cb2883037b6c003781b708fb1d9bc2e3d53bba480...,F,1958.0,1,1
9145,001c93d927eee9126c795e783226928ce902836ff583a9...,MISSING,NaN,0,1
9213,000fd0e0d8e230a667dde3893ea3926e4c0169f3c1bbb7...,F,1974.0,1,1
9426,00123b3afcecefc3c13c0b5cd19d513adac711bfeac967...,M,1983.0,1,1
9465,0018ea71afb9d0a18359cf772b9a8880af86f11ab0468d...,M,1962.0,1,1
9497,0011591577c1cb72194a729ef5b20786f416aacca62a78...,F,1972.0,1,1
9615,0007c77052ae6d9671dd7ecd987c4a3beb9dbec038be34...,M,1993.0,1,1
9632,00079d239ba743a0874475e182dbab0efcbbd27483ffe4...,M,1954.0,1,1
9685,000b6b83ec2000f7a075684fcf6fa66cf6b3acf6999525...,MISSING,1998.0,1,1